/**
 * Template-based fallback quiz, used when the offline pack can't be
 * generated by Gemini (no API key, free-tier quota exhausted, network
 * down, etc.). Builds up to 10 simple questions by reading structured
 * fields off the itinerary — no AI required, no network required, no
 * destination-specific copy. The kid still gets text + SFX even when
 * the fancy generator is offline.
 *
 * **Question philosophy** — every template is about one of three
 * things: a real *place* the family is visiting, a real *attraction*
 * (its description, its town, its tag), or a real *German word /
 * phrase* the day teaches. Meta-trip filler ("how many stops does
 * this day have?", "what day of the week is day 2?") is intentionally
 * absent — kids tune out instantly on questions about the data
 * structure of their own holiday.
 *
 * Each template:
 *   - takes the day + the rest of the itinerary as input,
 *   - returns a single `QuizQuestion` *only if* it has enough data
 *     to ask a meaningful question (otherwise returns null and the
 *     selector skips it),
 *   - sources its distractors from OTHER attractions / words / towns
 *     in the trip so wrong answers stay plausibly trip-flavored
 *     (the kid is choosing between four real Austrian places, not
 *     between Innsbruck and Madagascar).
 *
 * The selector then runs all templates, drops the nulls, deduplicates
 * by question text, and trims to the requested count. If we still
 * can't fill the count we just return what we got — the orchestrator
 * treats any non-empty fallback as playable.
 */

import { itinerary } from "../../data/itinerary";
import { attractions, getAttraction } from "../../data/attractions";
import { localizeDay, localizePoi } from "../../data/i18n";
import type {
  AttractionQuizFact,
  Day,
  ItalianWord,
  POI,
  Quiz,
  QuizQuestion
} from "../../data/types";
import type { Lang } from "../lang";
import { QUESTIONS_PER_OFFLINE_PACK } from "./generateQuiz";

const OPTIONS_PER_QUESTION = 4;

/** Per-language micro-dictionary — kept inside the module so the
 *  fallback works without the React `t()` hook (the module runs
 *  inside the orchestrator's startQuiz which is plain logic). Keep
 *  any new copy in sync with `dict.ts` if/when the React UI starts
 *  surfacing it. */
const COPY = {
  en: {
    correct: ["Bravo!", "Super!", "Genau!", "Perfekt!", "Jawohl!"],
    wrong: ["Close one!", "Almost!", "Not quite —", "Oof, nope —", "Ah, the answer is"],
    /** Friendly category labels for attraction tags, used to make
     *  questions like "Which of these is great for water adventures?". */
    tag: {
      water: "splashy water adventures",
      extreme: "thrills and adrenaline",
      nature: "nature walks and forests",
      culture: "old stories and history",
      family: "easy family fun",
      food: "tasting local food",
      view: "breathtaking views",
      cave: "exploring caves",
      village: "wandering an ancient village"
    } as Record<string, string>
  },
  he: {
    correct: ["בראבו!", "סופר!", "בדיוק!", "מושלם!", "יופי!"],
    wrong: ["קרוב!", "כמעט!", "לא ממש —", "אופ, לא —", "התשובה היא"],
    tag: {
      water: "הרפתקאות מים מרעננות",
      extreme: "ריגושים ואדרנלין",
      nature: "טבע ויערות",
      culture: "סיפורים והיסטוריה",
      family: "כיף משפחתי קליל",
      food: "טעימות אוכל מקומי",
      view: "נופים עוצרי נשימה",
      cave: "חקר מערות",
      village: "טיול בכפר עתיק"
    } as Record<string, string>
  }
} as const;

function pickReactions(
  lang: Lang,
  rng: () => number
): { reactionCorrect: string; reactionWrong: string } {
  const c = COPY[lang];
  const correct = c.correct[Math.floor(rng() * c.correct.length)];
  const wrong = c.wrong[Math.floor(rng() * c.wrong.length)];
  return { reactionCorrect: correct, reactionWrong: wrong };
}

/** Tiny seeded RNG so the same `(day, lang)` combo always produces
 *  the same fallback quiz — kid replaying gets the same set, no
 *  flicker, no surprises. mulberry32 is good enough for shuffles
 *  and 4-option picks; we don't need cryptographic strength here. */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** Pick `n` distractors from `pool`, skipping anything that matches
 *  `correct` (case-insensitive) and any duplicates. Returns fewer
 *  than `n` if the pool is too small — the template caller treats
 *  that as a "skip me" signal. */
function pickDistractors(
  pool: string[],
  correct: string,
  n: number,
  rng: () => number
): string[] {
  const seen = new Set<string>([correct.trim().toLowerCase()]);
  const candidates: string[] = [];
  for (const raw of pool) {
    const v = raw?.trim();
    if (!v) continue;
    const k = v.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    candidates.push(v);
  }
  shuffleInPlace(candidates, rng);
  return candidates.slice(0, n);
}

/** Wrap a question + correct answer + distractors into a real
 *  `QuizQuestion`, randomizing the slot the correct option sits in
 *  so the kid can't just tap the same letter every time. Returns
 *  null if we don't have enough distractors to make 4 options. */
function buildQ(opts: {
  lang: Lang;
  question: string;
  correct: string;
  distractors: string[];
  rng: () => number;
}): QuizQuestion | null {
  if (opts.distractors.length < OPTIONS_PER_QUESTION - 1) return null;

  const distractors = opts.distractors.slice(0, OPTIONS_PER_QUESTION - 1);
  const correctSlot = Math.floor(opts.rng() * OPTIONS_PER_QUESTION);
  const options: string[] = [];
  let dIdx = 0;
  for (let i = 0; i < OPTIONS_PER_QUESTION; i++) {
    if (i === correctSlot) {
      options.push(opts.correct);
    } else {
      options.push(distractors[dIdx++]);
    }
  }

  const reactions = pickReactions(opts.lang, opts.rng);
  return {
    question: opts.question,
    options,
    correctIndex: correctSlot,
    reactionCorrect: reactions.reactionCorrect,
    reactionWrong: `${reactions.reactionWrong} ${opts.correct}`
  };
}


/* ------------------------------------------------------------------ */
/* Austria-culture wildcard bank                                       */
/* ------------------------------------------------------------------ */

/** A small bilingual bank of kid-friendly "general Austria" facts —
 *  flag, food, mountains, animals, geography. Used by `tplAustriaCulture`
 *  as a controlled wildcard sprinkled into the offline pack so the
 *  deck doesn't feel repetitive on attraction-thin days. The pack is
 *  still primarily about today's attractions; the selector caps how
 *  many of these can fire (see `CULTURE_BUDGET` in `buildFallbackQuiz`).
 *  Keep facts at 8-year-old reading level — no politics, no booze,
 *  no scary detail. */
const AUSTRIA_CULTURE_FACTS: Record<Lang, AttractionQuizFact[]> = {
  en: [
    {
      question: "What are the colours on the Austrian flag, from top to bottom? (It's one of the oldest flags in the world!)",
      correctAnswer: "Red, white, and red",
      distractors: [
        "Green, white, and red",
        "Blue, white, and red",
        "Yellow, black, and white"
      ]
    },
    {
      question: "What is the capital city of Austria?",
      correctAnswer: "Vienna (Wien)",
      distractors: ["Salzburg", "Innsbruck", "Graz"]
    },
    {
      question: "The famous composer Mozart was born in which Austrian city?",
      correctAnswer: "Salzburg",
      distractors: ["Vienna", "Berlin", "Rome"]
    },
    {
      question: "What language do most people speak in Austria?",
      correctAnswer: "German",
      distractors: ["Italian", "French", "Spanish"]
    },
    {
      question: "Austria is famous for a huge mountain range that stretches across it. What is it called?",
      correctAnswer: "The Alps",
      distractors: ["The Andes", "The Rocky Mountains", "The Himalayas"]
    },
    {
      question: "In Austria, people often say 'Grüß Gott' or 'Servus'. What do these words mean?",
      correctAnswer: "Hello / greetings",
      distractors: ["Goodbye", "Thank you", "I'm hungry"]
    },
    {
      question: "Wiener Schnitzel is a famous Austrian food. What is it?",
      correctAnswer: "A thin, breaded and fried slice of meat",
      distractors: [
        "A chocolate cake",
        "A bowl of noodle soup",
        "A type of cheese"
      ]
    },
    {
      question: "Sachertorte is a world-famous cake from Vienna. What is it made of?",
      correctAnswer: "Chocolate cake with apricot jam",
      distractors: [
        "Cheese and tomato",
        "Banana and cream",
        "Strawberry ice cream"
      ]
    },
    {
      question: "Apfelstrudel is a beloved Austrian treat. What fruit is inside it?",
      correctAnswer: "Apples",
      distractors: ["Bananas", "Oranges", "Pineapples"]
    },
    {
      question: "The famous movie 'The Sound of Music' was filmed near which Austrian city?",
      correctAnswer: "Salzburg",
      distractors: ["Vienna", "Paris", "London"]
    },
    {
      question: "In the Alps, cows often wear something around their necks that jingles. What is it?",
      correctAnswer: "A cowbell",
      distractors: [
        "A scarf",
        "A necklace of flowers",
        "A little backpack"
      ]
    },
    {
      question: "Which furry animal lives high in the Alps and whistles loudly to warn its friends of danger?",
      correctAnswer: "The marmot",
      distractors: ["The penguin", "The camel", "The kangaroo"]
    },
    {
      question: "The ibex is a wild animal of the Alps. What is it?",
      correctAnswer: "A mountain goat with big curved horns",
      distractors: [
        "A giant fish",
        "A colourful parrot",
        "A tiny mouse"
      ]
    },
    {
      question: "Austria is one of the best places in the world for which snowy sport?",
      correctAnswer: "Skiing",
      distractors: ["Surfing", "Sandcastle building", "Scuba diving"]
    },
    {
      question: "A big, famous river flows through Vienna. What is it called?",
      correctAnswer: "The Danube",
      distractors: ["The Nile", "The Amazon", "The Thames"]
    },
    {
      question: "Edelweiss is a famous little white flower that grows in the Alps. Where does it like to grow?",
      correctAnswer: "High up on rocky mountains",
      distractors: [
        "At the bottom of the sea",
        "In hot sandy deserts",
        "Inside dark caves"
      ]
    },
    {
      question: "Yodeling is a special way of singing in the Alps. What does it sound like?",
      correctAnswer: "Quickly switching between low and very high notes",
      distractors: [
        "Whispering very softly",
        "Humming with a closed mouth",
        "Clapping in rhythm"
      ]
    },
    {
      question: "Kaiserschmarrn is a favourite Austrian dessert. What is it?",
      correctAnswer: "A fluffy pancake torn into pieces and dusted with sugar",
      distractors: [
        "A spicy vegetable soup",
        "A cold fruit salad",
        "A crunchy potato chip"
      ]
    },
    {
      question: "The famous energy drink Red Bull was invented in which country?",
      correctAnswer: "Austria",
      distractors: ["Brazil", "Japan", "Canada"]
    },
    {
      question: "In the Austrian mountains, how do people often travel up to the top to ski or enjoy the view?",
      correctAnswer: "In a cable car (gondola)",
      distractors: ["In a submarine", "On a camel", "In a hot-air balloon"]
    },
    {
      question: "The Tyrol region, surrounded by mountains, has a main city that hosted the Winter Olympics twice. What is it?",
      correctAnswer: "Innsbruck",
      distractors: ["Vienna", "Venice", "Munich"]
    },
    {
      question: "What is the name of the highest mountain in Austria?",
      correctAnswer: "The Grossglockner",
      distractors: ["Mount Everest", "Mount Fuji", "Table Mountain"]
    },
    {
      question: "In Austria, some people wear traditional leather shorts at festivals. What are they called?",
      correctAnswer: "Lederhosen",
      distractors: ["Pyjamas", "Raincoats", "Swimming trunks"]
    }
  ],
  he: [
    {
      question: "מהם צבעי דגל אוסטריה, מלמעלה למטה? (זהו אחד הדגלים העתיקים בעולם!)",
      correctAnswer: "אדום, לבן ואדום",
      distractors: ["ירוק, לבן ואדום", "כחול, לבן ואדום", "צהוב, שחור ולבן"]
    },
    {
      question: "מהי בירת אוסטריה?",
      correctAnswer: "וינה (Wien)",
      distractors: ["זלצבורג", "אינסברוק", "גראץ"]
    },
    {
      question: "המלחין המפורסם מוצרט נולד באיזו עיר אוסטרית?",
      correctAnswer: "זלצבורג",
      distractors: ["וינה", "ברלין", "רומא"]
    },
    {
      question: "באיזו שפה מדברים רוב האנשים באוסטריה?",
      correctAnswer: "גרמנית",
      distractors: ["איטלקית", "צרפתית", "ספרדית"]
    },
    {
      question: "אוסטריה מפורסמת ברכס הרים ענק שחוצה אותה. איך הוא נקרא?",
      correctAnswer: "האלפים",
      distractors: ["האנדים", "הרי הרוקי", "ההימלאיה"]
    },
    {
      question: "באוסטריה אומרים לעיתים קרובות 'גְרוּס גוֹט' או 'סֶרְווּס'. מה משמעות המילים האלה?",
      correctAnswer: "שלום / ברכת שלום",
      distractors: ["להתראות", "תודה", "אני רעב"]
    },
    {
      question: "שניצל וינאי הוא מאכל אוסטרי מפורסם. מה זה?",
      correctAnswer: "פרוסת בשר דקה מצופה בפירורי לחם ומטוגנת",
      distractors: [
        "עוגת שוקולד",
        "קערת מרק אטריות",
        "סוג של גבינה"
      ]
    },
    {
      question: "זאכרטורטה היא עוגה מפורסמת בעולם מווינה. ממה היא עשויה?",
      correctAnswer: "עוגת שוקולד עם ריבת משמש",
      distractors: [
        "גבינה ועגבנייה",
        "בננה וקצפת",
        "גלידת תות"
      ]
    },
    {
      question: "אפפלשטרודל הוא פינוק אוסטרי אהוב. איזה פרי יש בתוכו?",
      correctAnswer: "תפוחים",
      distractors: ["בננות", "תפוזים", "אננס"]
    },
    {
      question: "הסרט המפורסם 'צלילי המוזיקה' צולם ליד איזו עיר אוסטרית?",
      correctAnswer: "זלצבורג",
      distractors: ["וינה", "פריז", "לונדון"]
    },
    {
      question: "בהרי האלפים, פרות עונדות משהו על הצוואר שמצלצל. מה זה?",
      correctAnswer: "פעמון פרה",
      distractors: [
        "צעיף",
        "שרשרת פרחים",
        "תיק גב קטן"
      ]
    },
    {
      question: "איזו חיה פרוותית חיה גבוה באלפים ושורקת בקול כדי להזהיר את חבריה מסכנה?",
      correctAnswer: "המרמיטה",
      distractors: ["הפינגווין", "הגמל", "הקנגורו"]
    },
    {
      question: "היעל (איבֶּקְס) הוא חיית בר של האלפים. מה זה?",
      correctAnswer: "עז הרים עם קרניים גדולות ומעוקלות",
      distractors: [
        "דג ענק",
        "תוכי צבעוני",
        "עכבר קטנטן"
      ]
    },
    {
      question: "אוסטריה היא אחד המקומות הטובים בעולם לאיזה ספורט חורפי?",
      correctAnswer: "סקי",
      distractors: ["גלישת גלים", "בניית ארמונות חול", "צלילה"]
    },
    {
      question: "נהר גדול ומפורסם זורם דרך וינה. איך הוא נקרא?",
      correctAnswer: "הדנובה",
      distractors: ["הנילוס", "האמזונס", "התמזה"]
    },
    {
      question: "אדלווייס הוא פרח לבן וקטן מפורסם שגדל באלפים. איפה הוא אוהב לגדול?",
      correctAnswer: "גבוה על הרים סלעיים",
      distractors: [
        "בקרקעית הים",
        "במדבריות חול חמים",
        "בתוך מערות חשוכות"
      ]
    },
    {
      question: "יודל הוא דרך מיוחדת לשיר באלפים. איך זה נשמע?",
      correctAnswer: "מעבר מהיר בין צלילים נמוכים לגבוהים מאוד",
      distractors: [
        "לחישה חרישית מאוד",
        "פזמון בפה סגור",
        "מחיאות כפיים בקצב"
      ]
    },
    {
      question: "קייזרשמארן הוא קינוח אוסטרי אהוב. מה זה?",
      correctAnswer: "פנקייק אוורירי קרוע לחתיכות ומפוזר בסוכר",
      distractors: [
        "מרק ירקות חריף",
        "סלט פירות קר",
        "צ'יפס תפוחי אדמה"
      ]
    },
    {
      question: "משקה האנרגיה המפורסם רד בול הומצא באיזו מדינה?",
      correctAnswer: "אוסטריה",
      distractors: ["ברזיל", "יפן", "קנדה"]
    },
    {
      question: "בהרי אוסטריה, איך אנשים נוסעים לעיתים קרובות עד לפסגה כדי לגלוש או ליהנות מהנוף?",
      correctAnswer: "ברכבל (גונדולה)",
      distractors: ["בצוללת", "על גב גמל", "בכדור פורח"]
    },
    {
      question: "אזור טירול, המוקף בהרים, כולל עיר מרכזית שאירחה פעמיים את אולימפיאדת החורף. מהי?",
      correctAnswer: "אינסברוק",
      distractors: ["וינה", "ונציה", "מינכן"]
    },
    {
      question: "מה שמו של ההר הגבוה ביותר באוסטריה?",
      correctAnswer: "הגרוסגלוקנר",
      distractors: ["הר אוורסט", "הר פוג'י", "הר השולחן"]
    },
    {
      question: "באוסטריה, יש אנשים שלובשים מכנסי עור קצרים מסורתיים בחגיגות. איך הם נקראים?",
      correctAnswer: "לֶדֶרְהוֹזֶן",
      distractors: ["פיג'מה", "מעיל גשם", "בגד ים"]
    }
  ]
};

/* ------------------------------------------------------------------ */
/* Templates — ALL substantive (places / attractions / German)         */
/* ------------------------------------------------------------------ */

interface TemplateContext {
  lang: Lang;
  rng: () => number;
  day: Day;
  /** Other days, already localized. */
  otherDays: Day[];
  /** All attractions, already localized — used as a wide distractor
   *  pool. */
  allAttractions: POI[];
  /** Just the attractions the family visits *today*, localized.
   *  Templates use this for the "correct" answer when the question
   *  is grounded in the day's plan. */
  todaysAttractions: POI[];
}

/** Q: what does the German word X mean? */
function tplWordMeaning(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const words: ItalianWord[] = day.italianWords ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.meaning) return null;
  const otherMeanings = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.meaning))
    .filter(Boolean);
  const distractors = pickDistractors(
    otherMeanings,
    w.meaning,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `מה המשמעות של המילה הגרמנית "${w.word}"?`
        : `What does the German word "${w.word}" mean?`,
    correct: w.meaning,
    distractors,
    rng
  });
}

/** Q: how do you say [meaning] in German? — reverse of tplWordMeaning. */
function tplWordReverse(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const words: ItalianWord[] = day.italianWords ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.word || !w?.meaning) return null;
  const otherWords = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.word))
    .filter(Boolean);
  const distractors = pickDistractors(
    otherWords,
    w.word,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איך אומרים "${w.meaning}" בגרמנית?`
        : `How do you say "${w.meaning}" in German?`,
    correct: w.word,
    distractors,
    rng
  });
}

/** Q: which German phrase means "[example translation]"? */
function tplPhraseExample(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const phrases = (day.italianWords ?? []).filter(
    w => w.example && w.exampleMeaning
  );
  if (phrases.length === 0) return null;
  const w = phrases[Math.floor(rng() * phrases.length)];
  if (!w.example || !w.exampleMeaning) return null;
  const otherExamples = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.example).filter(Boolean))
    .filter((e): e is string => Boolean(e) && e !== w.example);
  const distractors = pickDistractors(
    otherExamples,
    w.example,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איזה משפט בגרמנית אומר "${w.exampleMeaning}"?`
        : `Which German phrase means "${w.exampleMeaning}"?`,
    correct: w.example,
    distractors,
    rng
  });
}

/** Q: a kid-friendly general "Austria" fact pulled from the
 *  `AUSTRIA_CULTURE_FACTS` bank above (flag colours, Vienna,
 *  Mozart, the Alps, Wiener Schnitzel, marmots, skiing, the
 *  Danube, …). The selector caps how many of these are allowed
 *  per pack (see `CULTURE_BUDGET`) — the deck stays primarily
 *  about the day's actual attractions, with one or two of these
 *  sprinkled in for variety on attraction-thin days. */
function tplAustriaCulture(ctx: TemplateContext): QuizQuestion | null {
  const { lang, rng } = ctx;
  const bank = AUSTRIA_CULTURE_FACTS[lang];
  if (!bank || bank.length === 0) return null;
  const fact = bank[Math.floor(rng() * bank.length)];
  return buildQ({
    lang,
    question: fact.question,
    correct: fact.correctAnswer,
    distractors: fact.distractors,
    rng
  });
}

/** Q: a hand-curated story / legend / signature-detail question
 *  about an attraction the family visits today. Pulls from the
 *  attraction's `quizFacts` array (authored alongside its
 *  description in `attractions.ts` + the HE overlay) — the
 *  template doesn't generate the question from text, it just lifts
 *  the curated fact and randomizes which option the correct answer
 *  lands in. This is the template that gets us the "Devil's Bridge
 *  → dog" class of question, and it's deliberately FIRST in the
 *  template list so it dominates the offline pack on any day with
 *  story-rich attractions. */
function tplAttractionStory(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, lang, rng } = ctx;
  // Build a flat (attraction, fact) catalog so we pick uniformly
  // across facts, not across attractions — otherwise an attraction
  // with 4 facts gets the same chance as one with 1 fact and we
  // end up overweighting the latter on multi-pass runs.
  type Pair = { att: POI; fact: AttractionQuizFact };
  const catalog: Pair[] = [];
  for (const att of todaysAttractions) {
    if (!att.quizFacts) continue;
    for (const fact of att.quizFacts) {
      if (!fact.question || !fact.correctAnswer) continue;
      if (!fact.distractors || fact.distractors.length < OPTIONS_PER_QUESTION - 1) continue;
      catalog.push({ att, fact });
    }
  }
  if (catalog.length === 0) return null;

  const pick = catalog[Math.floor(rng() * catalog.length)];
  // Distractor pool: the curated wrong answers from the SAME fact.
  // We don't blend in distractors from other facts because the
  // author already tuned these to be plausible-but-clearly-wrong
  // for THIS specific question (e.g. "A dog" vs "A cat / goat /
  // chicken" — mixing in an unrelated place would give it away).
  return buildQ({
    lang,
    question: pick.fact.question,
    correct: pick.fact.correctAnswer,
    distractors: pick.fact.distractors,
    rng
  });
}


const WORD_TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  tplWordMeaning,
  tplWordReverse,
  tplPhraseExample
];

const TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  // Curated story trivia first — when the attraction author has
  // written quizFacts for today's stops, these are the highest-
  // quality questions in the deck.
  tplAttractionStory
];

/* ------------------------------------------------------------------ */
/* Public entry point                                                  */
/* ------------------------------------------------------------------ */

/**
 * Build a fallback `Quiz` of up to `count` questions for `(day, lang)`,
 * deterministic per `(day, lang, count)`. Throws only if there is no
 * itinerary entry for the day at all (the orchestrator surfaces that
 * as a real error). If templates can't fill the requested count, the
 * returned quiz is shorter — the orchestrator treats any non-empty
 * fallback as playable.
 *
 * Each template can fire MULTIPLE times in one quiz (we re-run the
 * same set in shuffled order after the first pass, picking different
 * source items via the RNG) so a 10-question pack genuinely covers
 * 10 facts about the day instead of the 9 we'd get from one-shot
 * templates.
 */
export function buildFallbackQuiz(
  dayNumber: number,
  lang: Lang,
  count: number = QUESTIONS_PER_OFFLINE_PACK
): Quiz {
  const rawDay = itinerary.find(d => d.dayNumber === dayNumber);
  if (!rawDay) {
    throw new Error(`No itinerary entry for day ${dayNumber}`);
  }

  const day = lang === "he" ? localizeDay(rawDay, "he") : rawDay;
  const otherDays = itinerary
    .filter(d => d.dayNumber !== dayNumber)
    .map(d => (lang === "he" ? localizeDay(d, "he") : d));

  const pastDays = itinerary.filter(d => d.dayNumber <= dayNumber);
  const pastAttractionIds = new Set(
    pastDays.flatMap(d => d.activities.map(a => a.attractionId).filter(Boolean))
  );

  const allAttractions = attractions
    .filter(a => pastAttractionIds.has(a.id))
    .map(a => (lang === "he" ? localizePoi(a, "he") : a));

  // Today's attractions: pull every activity with an `attractionId`
  // and look it up. This gives us proper rich POIs (with shortDesc,
  // tags, address) instead of the bare activity titles, which is
  // what makes the questions actually about *places*.
  const todaysAttractions: POI[] = day.activities
    .map(a => (a.attractionId ? getAttraction(a.attractionId) : null))
    .filter((a): a is POI => Boolean(a))
    .map(a => (lang === "he" ? localizePoi(a, "he") : a));

  // Seed: day + lang + count. Picks a stable but unique RNG stream
  // for each combination.
  const seed = dayNumber * 1009 + (lang === "he" ? 7 : 13) + count * 31;
  const rng = mulberry32(seed);

  const ctx: TemplateContext = {
    lang,
    rng,
    day,
    otherDays,
    allAttractions,
    todaysAttractions
  };

  const collected: QuizQuestion[] = [];
  const seen = new Set<string>();
  const tryAdd = (q: QuizQuestion | null) => {
    if (!q) return;
    if (collected.length >= count) return;
    const key = q.question.trim().toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    collected.push(q);
  };

  // PASS 1 — Words (Target 2 questions). The user explicitly requested
  // 1-2 questions about German words learned today.
  const MAX_WORDS = todaysAttractions.length < 2 ? 1 : 2;
  let wordsAdded = 0;
  for (let pass = 0; pass < 3 && wordsAdded < MAX_WORDS && collected.length < count; pass++) {
    const order = shuffleInPlace([...WORD_TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (wordsAdded >= MAX_WORDS || collected.length >= count) break;
      const before = collected.length;
      tryAdd(WORD_TEMPLATES[idx](ctx));
      if (collected.length > before) wordsAdded++;
    }
  }

  // PASS 2 — Austria-culture wildcards (Target 4 questions, or more if few attractions).
  // The user explicitly requested 3-5 questions about general Austria
  // (flag, Vienna, Mozart, the Alps, geography). If there are very few
  // attractions today, fill the rest of the quiz with culture questions.
  const MAX_CULTURE = todaysAttractions.length < 2 ? (count - wordsAdded) : 4;
  let cultureAdded = 0;
  for (
    let i = 0;
    i < MAX_CULTURE * 4 && cultureAdded < MAX_CULTURE && collected.length < count;
    i++
  ) {
    const before = collected.length;
    tryAdd(tplAustriaCulture(ctx));
    if (collected.length > before) cultureAdded++;
  }

  // PASS 3 — Curated Attraction Stories. When attractions on this day
  // have hand-authored `quizFacts`, those are the highest-quality
  // questions about the specific attractions.
  for (let i = 0; i < 10 && collected.length < count; i++) {
    tryAdd(tplAttractionStory(ctx));
  }

  // PASS 4 — fill remaining slots with the diverse generic attraction templates
  // (description, town, tag, region).
  const MAX_PASSES = 4;
  for (let pass = 0; pass < MAX_PASSES && collected.length < count; pass++) {
    const order = shuffleInPlace([...TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (collected.length >= count) break;
      tryAdd(TEMPLATES[idx](ctx));
    }
  }

  // Finally, shuffle the collected questions so the different types
  // (words, culture, stories) are randomly mixed instead of clustered.
  shuffleInPlace(collected, rng);

  return {
    day: dayNumber,
    lang,
    questions: collected,
    // Marker timestamp 0 = "this is a fallback, not a real Gemini
    // generation". Anything reading the cache can distinguish if it
    // wants to (current orchestrator uses it to drive the banner).
    generatedAt: 0
  };
}
